name: Go
on: [ push ]

# ACTIONS_ID_TOKEN_REQUEST_TOKEN
# ACTIONS_ID_TOKEN_REQUEST_URL

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
# GITHUB_TOKEN secret auto-created (24h)
#

permissions:
  contents: write
  id-token: write # This is required for requesting the JWT
  #contents: read  # This is required for actions/checkout

env:
  GO111MODULE: on


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.21
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          env
          echo GIT TOKEN: ${{ secrets.GITHUB_TOKEN }}
          go test ./...

